[package]
name = "copy-service"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4"
actix-cors = "0.6.4"
tungstenite = "0.20.0"
askama = "0.12.0"
serde = { version = "1.0.104", features = ["derive"] }
serde_json = "1.0"
rand = "0.8.5"

